version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:45"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: truffle
    versions:
    - 5.1.63
    - 5.1.64
    - 5.1.65
    - 5.1.66
    - 5.1.67
    - 5.2.0
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
    - 5.3.0
    - 5.3.1
    - 5.3.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: solhint
    versions:
    - 3.3.2
    - 3.3.3
  - dependency-name: "@openzeppelin/contracts"
    versions:
    - 3.3.0
    - 3.4.0
    - 3.4.1
  - dependency-name: solidity-coverage
    versions:
    - 0.7.14
    - 0.7.15
  rebase-strategy: disabled
  registries:
  - npm-registry-registry-npmjs-org
